branch-defaults:
  master:
    environment: timetracking-dev
global:
  application_name: TimeTrackingService
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.09 v2.0.6 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
deploy:
  artifact: ./buildartifact.zip
