branch-defaults:
  development:
    environment: timetracking-dev
  master:
    environment: timetracking-prd
  release-0.29.0:
    environment: timetracking-stg
deploy:
  artifact: ./buildartifact.zip
environment-defaults:
  timetracking-stg:
    branch: null
    repository: null
global:
  application_name: TimeTrackingService
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.09 v2.0.6 running Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
